# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://wkevin.github.io/food.package/"

git_url = "https://github.com/wkevin/food.package/tree/master/"

def custom_doc_links(name): return None
